version: '3'
services:
  redis:
    image: redis:7.2.5
    restart: "no"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/redis.conf:/etc/redis/redis.conf
      - ./config/redis/data:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true